### ISSUE TITLE
Install Bob v2.0 on Ubuntu 14.04LTS ？

### ISSUE THREAD

**Issue by bzsy** [idiap/bob#196]
Hi，
 I have read the paper \<Bob: A Free Signal Processing and Machine Learning Toolbox for Researchers\>, and I am interested in it. But when I install this toolbox by myself, there is an problem.  The problem is described as follow:

*  Install Bob v2.0 on Ubuntu 14.04LTS

* All external dependencies are installed. (https://github.com/idiap/bob/wiki/Dependencies)

* In the process of intalling, I got a cue that the version of setuptools is too low,
so I install setuptools v8.3 (https://pypi.python.org/pypi/setuptools)

* In Python 2.7.6  and Python 3.4.0, when executing /bob-master/bin/buidout, the errors emerge ：

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/ABC/bob-master/eggs/zc.buildout-2.3.1-py3.4.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/home/ABC/bob-master/eggs/zc.buildout-2.3.1-py3.4.egg/zc/buildout/buildout.py", line 488, in install
    installed_develop_eggs = self._develop()
  File "/home/ABC/bob-master/eggs/zc.buildout-2.3.1-py3.4.egg/zc/buildout/buildout.py", line 730, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/ABC/bob-master/eggs/bob.buildout-2.0.1-py3.4.egg/bob/buildout/extension.py", line 212, in develop
    zc.buildout.easy_install.call_subprocess(args)
  File "/home/ABC/bob-master/eggs/zc.buildout-2.3.1-py3.4.egg/zc/buildout/easy_install.py", line 159, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/usr/bin/python3', '/tmp/tmp5v2u3945', '-v', 'develop', '-mxN', '-d', '/home/ABC/bob-master/develop-eggs/tmpjdlacslcbuild'
```

THX a lot.

**Comment by siebenkopf** [comment]
We had some trouble with buildout, where the authors of that package have lately changed the `bootstrap.py` to `bootstrap-buildout.py`. Your issues might be related to that.

We have now corrected the installation instructions in https://github.com/idiap/bob/wiki. I hope that this solves your problem. As usual, try to clean up everything and start the build process from scratch.

**Comment by StevenLobo2** [comment]
I am still facing the issue on Mac OS X . What changes need to be made for configuration file?

**Comment by anjos** [comment]
No feedback on this one after 2 months. @StevenLobo2, please check discussion about your OS X issue in the other bug. I'll close this one. Otherwise, please start a thread at our mailing list: https://groups.google.com/forum/?fromgroups#!forum/bob-devel
